### PR TITLE
Move datatable tranfom into Table class.

### PR DESCRIPTION
**Pull request by pplancq**
Hello,

I think that when generating the datatable, the raw data retrieved from the gerkin file should not be transformed.

For this I propose to move the transformation logic directly into the datatable classes.

Here I only dealt with HTable.

Thanks to this, it is now possible to retrieve the raw data from the HTable.

If you are ok with this change I could take care of the VTable, MTable and ListTable.

### CODE REVIEW

**Comment by Bendat** [comment]
Interesting idea. Feel free to apply it to the other tables. I'll try play around with this branch and if it all makes sense we can consider merging this change

**Comment by pplancq** [comment]
I agree, I had hesitated to use a method like getRaw, so as not to break the operation.

I will change this to apply to the other class.

Glad you like my submissions

Personally I find your project very interesting especially the cucumber runner party which is a very good alternative to jest-cucumber which no longer seems to be maintained.

**Comment by pplancq** [comment]
Hello,

I made my modification in the other class (VTable, MTable)

I did not implement a `getRaw` method because after reflection I wonder if it is relevant.

At the same time, I removed the transformation from the example datatables so that the interpolation remains as raw as possible.

I remain open to improvements.

**Comment by Bendat** [comment]
Hello, apologies for the slow responsiveness, quite busy lately. Hoping to take a look at this soon

**Comment by pplancq** [comment]
Hello,

no problem, take your time. This represents a major change in your initial approach so better be sure before you merge

**Comment by Bendat** [comment]
Please be advised that data table implementations will be updated in a future release: 

https://github.com/Bendat/autometa/tree/main/packages/gherkin/src/steps/datatables

I'll need to look more deeply into this to figure out if they're compatible or incompatible. I can still update the existing framework with this change though

**Comment by pplancq** [comment]
Hello @Bendat , thank you for your answer.

At first sight your new implementation looks like the one I propose.

After that will depend on when you will integrate this package into the runner,
if it's a matter of 2 or 3 weeks we can wait,
but if it is longer we could consider merging this PR in order to have this functionality active.

I don't hide from you that I would like to present your library within my company, because I would like to replace the jest-cucumber lib (which no longer seems to be maintained) with yours which is very promising.

**Comment by Bendat** [comment]
Going to merge this. I'll try cut a release shortly after. I appreciate your appreciation of the library. Likewise it was spawned from the same frustration

**Pull request merged**
